### PR TITLE
adding more international country

### PR DESCRIPTION
**Pull request by AmirolAhmad**
I hope there is another way to clean up the country code array coz maybe in the future we can add more country in the better way LOL :kissing:

### CODE REVIEW

**Comment by amree** [comment]
Agree. I was planning to extract the country list to its own file and just require it from `app.rb`. But I haven't read about best practise in Sinatra regarding it.

My initial plan was using hash, for e.g:

```
>> hash = { "Country A" => ["Airport1", "Airport2"],
..     "Country B" => ["Airport1", "Airport2"],
..     "Country C" => ["Airpot1", "Airport2"] }
```

Select2 also supports the usage of `optgroup` tag, so, we can group these aiports in its own group (which is country). I also want to make a helper in rendering these countries. Less ruby code in the template would be great.

Damn, too much things on the todo list, lol.

But I'll merge this one first untill a better way is found

**Comment by amree** [comment]
Eh, I didn't realize you're already using `optgroup`, cool :+1:

**Comment by AmirolAhmad** [comment]
haha in the meantime, we can try looking a better way.. :)

**Comment by AmirolAhmad** [comment]
aku dh buat helper untuk country airport listing.. its works fine semua tp but when i search the flight, it gives me the error. related to the teecket gem. wanna take a look? i prefer merge this commit first (kalau aku push ke repo aku, dia auto pull request skali masuk sini lol), then nti untuk yg error aku ckp ni, aku bukak issue n pr ntok ko tgk lebih lanjut.. amcm?

**Comment by amree** [comment]
:+1: Ok jap, aku merge (tak sempat pull and test local lagi). We need tests, next time lol

**Pull request merged**
