### PR TITLE
#3 friendly error message page

### PR DESCRIPTION
**Pull request by AmirolAhmad**

### CODE REVIEW

**Comment by amree** [comment]
Peh, selesai masalah gini. Aku merge dulu. Honestly, aku ada plan lain bab loading tu, tapi yang ni ok dulu, cuma font size dia problem bila bukak di phone

screenshot_2015-06-16-22-20-00

**Comment by AmirolAhmad** [comment]
i see.. haha aku ingtkan ko xde plan ntok loading tu.. takpe2 nti bleh tukar guna ko nye idea lak huhu

On June 16, 2015 at 10:24:07 PM, Mohd Amree (notifications@github.com) wrote:

Peh, selesai masalah gini. Aku merge dulu. Honestly, aku ada plan lain bab loading tu, tapi yang ni ok dulu, cuma font size dia problem bila bukak di phone

—
Reply to this email directly or view it on GitHub.

---

Best regards,

AmirolAhmad
Software Engineer

Mobile Phone: (+60) 19 515 1707
Website: http://mramirol.com
Facebook: https://www.facebook.com/AmirolAhmad
Twitter: https://twitter.com/AmirolAhmad
Linkedin: http://www.linkedin.com/in/amirolahmad

**Comment by amree** [comment]
Tak, tak tau bila lagi. Aku nak merge yang ni dulu, at least nampak loading tu, cuma ko tolong fix bab font besar tu, hehe, nanti aku bukak isu untuk diskusi planning

**Comment by AmirolAhmad** [comment]
haha ok bleh2 xde hal.. nti aku make it responsive

**Comment by amree** [comment]
:+1: Hehe

**Comment by AmirolAhmad** [comment]
ok done for responsive huhu

**Comment by amree** [comment]
Hebat :+1: Ok, aku merge

**Pull request merged**
